Basic:
    phoneme_type: True
    
    #only available when character mode triggered
    char_path: ./asset/dict/ko.json
    train_img_path: ../SynthText_kr/result/
    
Model:
    hidden_size: 1024
    output_size: 512
    input_size: 3
    use_tp: False
    
Program:
    batch_size: 5
    epochs: 10
    learning_rate: 0.0003
    save_path: ./result/
    saved_model: ./result/char/model_para:False_0.0003.pth

    # Data Setting
    row_max: 750
    col_count: 5
    